### ISSUE TITLE
Require taking cover

### ISSUE THREAD

**Issue by PeterDrake** [PeterDrake/quoke_game1#10]
Have the falling debris continue and increase until the player gets under the table.

**Comment by peterhuizenga** [comment]
Done! Debris continue to fall more intensely until player hides under table... Rates of falling, where items fall, what items are falling, etc. could be tweaked further with future testing.

**Comment by PeterDrake** [comment]
Let's make sure to drop one directly on the player after a while.

**Comment by peterhuizenga** [comment]
Done on branch peterh

**Comment by peterhuizenga** [comment]
Please re-pull, important bug fix
