### ISSUE TITLE
Move conversation-closing red X

### ISSUE THREAD

**Issue by PeterDrake** [PeterDrake/quoke_game1#23]
Make it obvious that it's associated with the conversation dialog box.

**Comment by peterhuizenga** [comment]
I might remove the red X..... closing a dialogue early messes up the new Head/seen dialogue logic... this could potentially be reworked, but when would a player close a dialogue early/ do we want them to? If they are re-opening a dialogue it will give them a new head that is either short or provides new relevant information, so it wouldn't be a convenience thing i.e. a player never will just have to rapidly click through new dialogue to close, so I'm not sure we need the exit function/ it really provides anything

**Comment by PeterDrake** [comment]
Yeah, that sounds like a good argument for just getting rid of it.

**Comment by peterhuizenga** [comment]
Red x removed on branch peterh
